/// Built-in tool documentation rendered into CLAUDE.md / AGENTS.md / GEMINI.md.
///
/// These sections are generated by the server — not stored as knowledge entries.
/// They serve two purposes:
/// 1. Teach workflow patterns (HOW/WHEN/WHY), not just tool descriptions
/// 2. List all tools so deferred-loading LLMs discover them before improvising

pub fn builtin_preamble(provider: &str) -> String {
    let mut sections = Vec::new();

    sections.push(knowledge_section());
    sections.push(transcript_section());
    sections.push(threads_section());
    sections.push(orchestration_section());

    // Provider-specific notes
    match provider {
        "codex" | "agents" => {
            sections.push(codex_notes());
        }
        _ => {}
    }

    sections.join("\n\n")
}

fn knowledge_section() -> String {
    r#"## Tools

This file is generated by blackbox. Do not edit directly.

**Knowledge persistence:** When you learn something durable — a preference, convention, workflow rule, or project fact — persist it:
- `bbox_learn` — teaches all agents. Entry is rendered into CLAUDE.md/AGENTS.md/GEMINI.md. Use for instructions, conventions, and rules that should be in every session's context.
- `bbox_remember` — files for later recall. Entry is indexed and searchable via `bbox_knowledge` but never rendered. Use for observations, decisions, context, and notes that are useful on-demand but don't need to burn context budget every session.
- `bbox_knowledge` — recall stored knowledge. Search before guessing. Query by category, project, or free text.

**When to use which:** If you'd want this in CLAUDE.md, use `learn`. If you'd want to grep for it later, use `remember`. When unsure, `remember` is safer — it can be promoted to `learn` later.

**Invariants:** For safety rules or constraints that must never silently expire, set `decay: false`. Example: "never kill processes by port" is an invariant.

**Additional knowledge tools:** `bbox_forget` (retire entry), `bbox_render` (re-render markdown), `bbox_absorb` (ingest external edits), `bbox_lint` (health check), `bbox_review` (approve/reject unverified), `bbox_bootstrap` (onboard new repo)."#.into()
}

fn transcript_section() -> String {
    r#"**Transcript search:** When the user asks about past conversations ("when did we discuss X", "find the session where Y", "what did codex say about Z"), use the bbox transcript tools. Do NOT write ad-hoc Python to parse JSONL transcript files.
- `bbox_search` — find conversations by keyword/phrase, filterable by account/role/project
- `bbox_messages` — read a session's conversation flow (supports pagination, role filter, tail mode)
- `bbox_context` — zoom into surrounding messages from a search hit
- `bbox_session` — session metadata (duration, tool usage, first prompt)
- `bbox_sessions_list` — browse all sessions by account/project/name
- `bbox_topics` — top terms by frequency (no LLM, pure counting)
- `bbox_stats` — corpus statistics (doc count, index size)
- `bbox_reindex` — trigger incremental or full index rebuild

Covers all Claude Code accounts + Codex CLI sessions in a single index. Roles: `user` (human-typed), `assistant`, `thinking`, `tool_use`, `tool_result`, `developer` (Codex system context)."#.into()
}

fn threads_section() -> String {
    r#"**Work threads:** Track non-dispatchable work (debugging, QC walks, investigations) across sessions.
- `bbox_thread` — open/continue/resolve/promote work threads. Actions: get, open, continue, link, resolve, promote, rename.
- `bbox_thread_list` — list threads by status/project, find stale/abandoned work."#.into()
}

fn orchestration_section() -> String {
    r#"**Agent orchestration (bro):** Dispatch and coordinate work across multiple AI providers.

Core workflow:
- `bro_exec` — launch a task. Returns {taskId, sessionId} immediately. Prefer targeting a named bro (`bro: "alice"`) over raw provider.
- `bro_resume` — continue an existing session with a follow-up. Uses `resume` not `exec` for multi-turn conversations.
- `bro_wait` — block until a task completes. USE MAXIMUM TIMEOUT.
- `bro_when_all` — block until ALL tasks complete. Use after broadcast for blind deliberation.
- `bro_when_any` — block until FIRST task completes. Use for racing providers.
- `bro_broadcast` — send same prompt to every team member. Follow with when_all or when_any.

Management:
- `bro_status` — non-blocking progress check
- `bro_dashboard` — list recent tasks (filterable by provider, team, status)
- `bro_cancel` — kill a running task
- `bro_providers` — list configured providers and available models

Configuration:
- `bro_brofile` — manage brofile templates (provider + account + lens/personality). Actions: create, list, get, delete, set_account, list_accounts.
- `bro_team` — manage teamplates and teams. Actions: save_template, list_templates, delete_template, create, list, dissolve, roster.

**Key patterns:**
- **broadcast → when_all**: blind deliberation, provider comparison (fan-out / fan-in)
- **broadcast → when_any**: racing providers, fast-path resolution (first result wins)
- **Individual exec/resume**: direct steering of a specific bro mid-workflow
- **Multi-round**: freely interleave broadcast (ensemble) and resume (individual)
- Always use `resume` (not `exec`) for multi-turn conversations — `exec` starts fresh with no memory
- Named bro targeting resolves provider, account, lens, and sessionId automatically"#.into()
}

fn codex_notes() -> String {
    r#"**Codex-specific:** Roles map as: `user` → human input, `assistant` → model output, `developer` → system context, `tool_use`/`tool_result` → function calls."#.into()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_preamble_contains_all_sections() {
        let preamble = builtin_preamble("claude");
        assert!(preamble.contains("bbox_learn"));
        assert!(preamble.contains("bbox_search"));
        assert!(preamble.contains("bbox_thread"));
        assert!(preamble.contains("bro_exec"));
        assert!(preamble.contains("bro_broadcast"));
        assert!(preamble.contains("bro_brofile"));
        assert!(preamble.contains("bro_team"));
    }

    #[test]
    fn test_preamble_codex_has_notes() {
        let preamble = builtin_preamble("codex");
        assert!(preamble.contains("Codex-specific"));
    }

    #[test]
    fn test_preamble_claude_no_codex_notes() {
        let preamble = builtin_preamble("claude");
        assert!(!preamble.contains("Codex-specific"));
    }

    #[test]
    fn test_all_bbox_tools_listed() {
        let preamble = builtin_preamble("claude");
        let expected_tools = [
            "bbox_learn", "bbox_remember", "bbox_knowledge", "bbox_forget",
            "bbox_render", "bbox_absorb", "bbox_lint", "bbox_review", "bbox_bootstrap",
            "bbox_search", "bbox_messages", "bbox_context", "bbox_session",
            "bbox_sessions_list", "bbox_topics", "bbox_stats", "bbox_reindex",
            "bbox_thread", "bbox_thread_list",
        ];
        for tool in &expected_tools {
            assert!(preamble.contains(tool), "Missing tool: {tool}");
        }
    }

    #[test]
    fn test_all_bro_tools_listed() {
        let preamble = builtin_preamble("claude");
        let expected_tools = [
            "bro_exec", "bro_resume", "bro_wait", "bro_when_all", "bro_when_any",
            "bro_broadcast", "bro_status", "bro_dashboard", "bro_cancel",
            "bro_providers", "bro_brofile", "bro_team",
        ];
        for tool in &expected_tools {
            assert!(preamble.contains(tool), "Missing tool: {tool}");
        }
    }
}
