use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Built-in tool documentation rendered into CLAUDE.md / AGENTS.md / GEMINI.md.
///
/// These sections are generated by the server — not stored as knowledge entries.
/// They serve two purposes:
/// 1. Teach workflow patterns (HOW/WHEN/WHY), not just tool descriptions
/// 2. List all tools so deferred-loading LLMs discover them before improvising
pub const MANAGED_START: &str = "<!-- bb:managed-start -->";
pub const MANAGED_END: &str = "<!-- bb:managed-end -->";

/// Resolve global-memory destinations per provider. Returns `None` for
/// providers without a defined global memory file (copilot reads project
/// files only; vibe is intentionally unsupported per design).
///
/// Env overrides take precedence over defaults:
/// `BLACKBOX_GLOBAL_CLAUDE_MD`, `BLACKBOX_GLOBAL_CODEX_MD`,
/// `BLACKBOX_GLOBAL_GEMINI_MD`.
pub fn global_target_path(provider: &str) -> Option<Result<PathBuf>> {
    let resolve = |env_key: &str, default_fn: &dyn Fn() -> Result<PathBuf>| -> Result<PathBuf> {
        if let Ok(v) = std::env::var(env_key) {
            return Ok(PathBuf::from(v));
        }
        default_fn()
    };

    let home = || dirs::home_dir().context("home directory not found");

    match provider {
        "claude" => Some(resolve("BLACKBOX_GLOBAL_CLAUDE_MD", &|| {
            let h = home()?;
            let shared = h.join(".claude-shared");
            Ok(if shared.is_dir() {
                shared.join("CLAUDE.md")
            } else {
                h.join(".claude").join("CLAUDE.md")
            })
        })),
        // "agents" is the render umbrella that produces AGENTS.md content;
        // globally, the only auto-loading consumer is Codex.
        "codex" | "agents" => Some(resolve("BLACKBOX_GLOBAL_CODEX_MD", &|| {
            Ok(home()?.join(".codex").join("AGENTS.md"))
        })),
        "gemini" => Some(resolve("BLACKBOX_GLOBAL_GEMINI_MD", &|| {
            Ok(home()?.join(".gemini").join("GEMINI.md"))
        })),
        _ => None,
    }
}

/// Outcome of a managed-region patch.
#[derive(Debug, Clone, PartialEq)]
pub enum PatchOutcome {
    /// File didn't exist; created with managed region as full content.
    Created,
    /// File existed without markers; managed region appended at end.
    Appended,
    /// File existed with markers; content between markers replaced.
    Replaced,
    /// New content matches existing managed region; nothing written.
    Unchanged,
}

#[derive(Debug, Clone)]
pub struct PatchPlan {
    pub path: PathBuf,
    pub outcome: PatchOutcome,
    pub before: Option<String>,
    pub after: String,
}

impl PatchPlan {
    pub fn summary(&self) -> String {
        match self.outcome {
            PatchOutcome::Created => format!("CREATE {} ({} chars)", self.path.display(), self.after.len()),
            PatchOutcome::Appended => format!(
                "APPEND managed region to {} (existing {} chars, adding {} chars)",
                self.path.display(),
                self.before.as_deref().map_or(0, str::len),
                self.after.len()
            ),
            PatchOutcome::Replaced => format!(
                "REPLACE managed region in {} ({} chars → {} chars)",
                self.path.display(),
                self.before.as_deref().map_or(0, str::len),
                self.after.len()
            ),
            PatchOutcome::Unchanged => format!("UNCHANGED {}", self.path.display()),
        }
    }
}

/// Compute what a managed-region patch would do without writing anything.
/// `managed_body` is the bbox-rendered content (without markers).
pub fn plan_managed_patch(file_path: &Path, managed_body: &str) -> Result<PatchPlan> {
    let new_block = format!("{MANAGED_START}\n{}\n{MANAGED_END}", managed_body.trim_end());

    if !file_path.exists() {
        return Ok(PatchPlan {
            path: file_path.to_path_buf(),
            outcome: PatchOutcome::Created,
            before: None,
            after: new_block,
        });
    }

    let existing = fs::read_to_string(file_path)
        .with_context(|| format!("reading {}", file_path.display()))?;
    let (start_idx, end_idx) = find_marker_positions(&existing)?;

    match (start_idx, end_idx) {
        (Some(s), Some(e)) => {
            let existing_block = existing[s..e + MANAGED_END.len()].to_string();
            if existing_block == new_block {
                Ok(PatchPlan {
                    path: file_path.to_path_buf(),
                    outcome: PatchOutcome::Unchanged,
                    before: Some(existing_block),
                    after: new_block,
                })
            } else {
                Ok(PatchPlan {
                    path: file_path.to_path_buf(),
                    outcome: PatchOutcome::Replaced,
                    before: Some(existing_block),
                    after: new_block,
                })
            }
        }
        (None, None) => Ok(PatchPlan {
            path: file_path.to_path_buf(),
            outcome: PatchOutcome::Appended,
            before: Some(existing),
            after: new_block,
        }),
        _ => anyhow::bail!(
            "{}: unbalanced managed-region markers — refusing to patch",
            file_path.display()
        ),
    }
}

/// Apply a `PatchPlan`. Snapshots the original (if it existed) to the backup
/// directory before writing. Returns the backup path (if a snapshot was taken).
pub fn apply_managed_patch(plan: &PatchPlan) -> Result<Option<PathBuf>> {
    let backup = if plan.path.exists() {
        Some(snapshot_file(&plan.path)?)
    } else {
        None
    };

    let new_contents = match plan.outcome {
        PatchOutcome::Unchanged => return Ok(backup),
        PatchOutcome::Created => format!("{}\n", plan.after),
        PatchOutcome::Appended => {
            let existing = plan.before.as_deref().unwrap_or("");
            let sep = if existing.ends_with("\n\n") {
                ""
            } else if existing.ends_with('\n') {
                "\n"
            } else if existing.is_empty() {
                ""
            } else {
                "\n\n"
            };
            format!("{existing}{sep}{}\n", plan.after)
        }
        PatchOutcome::Replaced => {
            let existing = plan.before.as_deref().unwrap_or("");
            let full = fs::read_to_string(&plan.path)?;
            let (s, e) = find_marker_positions(&full)?;
            let s = s.expect("planned Replace requires markers");
            let e = e.expect("planned Replace requires markers");
            let mut out = String::with_capacity(full.len() + plan.after.len());
            out.push_str(&full[..s]);
            out.push_str(&plan.after);
            out.push_str(&full[e + MANAGED_END.len()..]);
            // Light hygiene: ensure the file ends with a single newline.
            if !out.ends_with('\n') {
                out.push('\n');
            }
            // Sanity: existing block content should match what we planned against.
            let _ = existing;
            out
        }
    };

    if let Some(parent) = plan.path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).ok();
        }
    }
    write_atomic(&plan.path, &new_contents)?;
    Ok(backup)
}

fn find_marker_positions(text: &str) -> Result<(Option<usize>, Option<usize>)> {
    let starts: Vec<_> = text.match_indices(MANAGED_START).collect();
    let ends: Vec<_> = text.match_indices(MANAGED_END).collect();
    if starts.len() > 1 || ends.len() > 1 {
        anyhow::bail!("multiple managed-region markers found");
    }
    Ok((starts.first().map(|(i, _)| *i), ends.first().map(|(i, _)| *i)))
}

/// Snapshot a file to `~/.local/state/blackbox/backups/<ISO-ts>/<filename>`.
/// Returns the destination path. Creates parent dirs as needed.
pub fn snapshot_file(src: &Path) -> Result<PathBuf> {
    let backup_root = backup_root()?;
    let stamp = chrono::Utc::now().format("%Y%m%dT%H%M%SZ").to_string();
    let dir = backup_root.join(stamp);
    fs::create_dir_all(&dir)?;
    let name = src
        .file_name()
        .context("source path has no file name")?;
    let dest = dir.join(name);
    fs::copy(src, &dest)
        .with_context(|| format!("backing up {} → {}", src.display(), dest.display()))?;
    Ok(dest)
}

fn backup_root() -> Result<PathBuf> {
    if let Ok(v) = std::env::var("BLACKBOX_BACKUP_DIR") {
        return Ok(PathBuf::from(v));
    }
    let state = dirs::state_dir()
        .or_else(|| dirs::home_dir().map(|h| h.join(".local/state")))
        .context("could not locate state dir")?;
    Ok(state.join("blackbox").join("backups"))
}

fn write_atomic(path: &Path, content: &str) -> Result<()> {
    let tmp = path.with_extension("md.tmp");
    let mut file = fs::File::create(&tmp)
        .with_context(|| format!("creating {}", tmp.display()))?;
    file.write_all(content.as_bytes())?;
    file.sync_all()?;
    drop(file);
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} → {}", tmp.display(), path.display()))?;
    Ok(())
}

pub fn builtin_preamble(provider: &str) -> String {
    let mut sections = Vec::new();

    sections.push(knowledge_section());
    sections.push(transcript_section());
    sections.push(threads_section());
    sections.push(orchestration_section());

    // Provider-specific notes
    match provider {
        "codex" | "agents" => {
            sections.push(codex_notes());
        }
        _ => {}
    }

    sections.join("\n\n")
}

fn knowledge_section() -> String {
    r#"## Tools

This file is generated by blackbox. Do not edit directly.

**Knowledge persistence:** When you learn something durable — a preference, convention, workflow rule, or project fact — persist it:
- `bbox_learn` — teaches all agents. Entry is rendered into CLAUDE.md/AGENTS.md/GEMINI.md. Use for instructions, conventions, and rules that should be in every session's context.
- `bbox_remember` — files for later recall. Entry is indexed and searchable via `bbox_knowledge` but never rendered. Use for observations, decisions, context, and notes that are useful on-demand but don't need to burn context budget every session.
- `bbox_knowledge` — recall stored knowledge. Search before guessing. Query by category, project, or free text.

**When to use which:** If you'd want this in CLAUDE.md, use `learn`. If you'd want to grep for it later, use `remember`. When unsure, `remember` is safer — it can be promoted to `learn` later.

**Invariants:** For safety rules or constraints that must never silently expire, set `decay: false`. Example: "never kill processes by port" is an invariant.

**Additional knowledge tools:** `bbox_forget` (retire entry), `bbox_render` (re-render markdown), `bbox_absorb` (ingest external edits), `bbox_lint` (health check), `bbox_review` (approve/reject unverified), `bbox_bootstrap` (onboard new repo)."#.into()
}

fn transcript_section() -> String {
    r#"**Transcript search:** When the user asks about past conversations ("when did we discuss X", "find the session where Y", "what did codex say about Z"), use the bbox transcript tools. Do NOT write ad-hoc Python to parse JSONL transcript files.
- `bbox_search` — find conversations by keyword/phrase, filterable by account/role/project
- `bbox_messages` — read a session's conversation flow (supports pagination, role filter, tail mode)
- `bbox_context` — zoom into surrounding messages from a search hit
- `bbox_session` — session metadata (duration, tool usage, first prompt)
- `bbox_sessions_list` — browse all sessions by account/project/name
- `bbox_topics` — top terms by frequency (no LLM, pure counting)
- `bbox_stats` — corpus statistics (doc count, index size)
- `bbox_reindex` — trigger incremental or full index rebuild

Covers all Claude Code accounts + Codex CLI sessions in a single index. Roles: `user` (human-typed), `assistant`, `thinking`, `tool_use`, `tool_result`, `developer` (Codex system context)."#.into()
}

fn threads_section() -> String {
    r#"**Work threads:** Track non-dispatchable work (debugging, QC walks, investigations) across sessions.
- `bbox_thread` — open/continue/resolve/promote work threads. Actions: get, open, continue, link, resolve, promote, rename.
- `bbox_thread_list` — list threads by status/project, find stale/abandoned work."#.into()
}

fn orchestration_section() -> String {
    r#"**Agent orchestration (bro):** Dispatch and coordinate work across multiple AI providers.

Core workflow:
- `bro_exec` — launch a task. Returns {taskId, sessionId} immediately. Prefer targeting a named bro (`bro: "alice"`) over raw provider.
- `bro_resume` — continue an existing session with a follow-up. Uses `resume` not `exec` for multi-turn conversations.
- `bro_wait` — block until a task completes. USE MAXIMUM TIMEOUT.
- `bro_when_all` — block until ALL tasks complete. Use after broadcast for blind deliberation.
- `bro_when_any` — block until FIRST task completes. Use for racing providers.
- `bro_broadcast` — send same prompt to every team member. Follow with when_all or when_any.

Management:
- `bro_status` — non-blocking progress check
- `bro_dashboard` — list recent tasks (filterable by provider, team, status)
- `bro_cancel` — kill a running task
- `bro_providers` — list configured providers and available models

Configuration:
- `bro_brofile` — manage brofile templates (provider + account + lens/personality). Actions: create, list, get, delete, set_account, list_accounts.
- `bro_team` — manage teamplates and teams. Actions: save_template, list_templates, delete_template, create, list, dissolve, roster.

**Key patterns:**
- **broadcast → when_all**: blind deliberation, provider comparison (fan-out / fan-in)
- **broadcast → when_any**: racing providers, fast-path resolution (first result wins)
- **Individual exec/resume**: direct steering of a specific bro mid-workflow
- **Multi-round**: freely interleave broadcast (ensemble) and resume (individual)
- Always use `resume` (not `exec`) for multi-turn conversations — `exec` starts fresh with no memory
- Named bro targeting resolves provider, account, lens, and sessionId automatically"#.into()
}

fn codex_notes() -> String {
    r#"**Codex-specific:** Roles map as: `user` → human input, `assistant` → model output, `developer` → system context, `tool_use`/`tool_result` → function calls."#.into()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_preamble_contains_all_sections() {
        let preamble = builtin_preamble("claude");
        assert!(preamble.contains("bbox_learn"));
        assert!(preamble.contains("bbox_search"));
        assert!(preamble.contains("bbox_thread"));
        assert!(preamble.contains("bro_exec"));
        assert!(preamble.contains("bro_broadcast"));
        assert!(preamble.contains("bro_brofile"));
        assert!(preamble.contains("bro_team"));
    }

    #[test]
    fn test_preamble_codex_has_notes() {
        let preamble = builtin_preamble("codex");
        assert!(preamble.contains("Codex-specific"));
    }

    #[test]
    fn test_preamble_claude_no_codex_notes() {
        let preamble = builtin_preamble("claude");
        assert!(!preamble.contains("Codex-specific"));
    }

    #[test]
    fn test_all_bbox_tools_listed() {
        let preamble = builtin_preamble("claude");
        let expected_tools = [
            "bbox_learn", "bbox_remember", "bbox_knowledge", "bbox_forget",
            "bbox_render", "bbox_absorb", "bbox_lint", "bbox_review", "bbox_bootstrap",
            "bbox_search", "bbox_messages", "bbox_context", "bbox_session",
            "bbox_sessions_list", "bbox_topics", "bbox_stats", "bbox_reindex",
            "bbox_thread", "bbox_thread_list",
        ];
        for tool in &expected_tools {
            assert!(preamble.contains(tool), "Missing tool: {tool}");
        }
    }

    #[test]
    fn test_patch_plan_creates_when_missing() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        let plan = plan_managed_patch(&p, "hello\nworld").unwrap();
        assert_eq!(plan.outcome, PatchOutcome::Created);
        assert!(plan.before.is_none());
        assert!(plan.after.contains(MANAGED_START));
        assert!(plan.after.contains(MANAGED_END));
        assert!(plan.after.contains("hello"));
    }

    #[test]
    fn test_patch_plan_appends_when_no_markers() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(&p, "user prose\n@RTK.md\n").unwrap();
        let plan = plan_managed_patch(&p, "managed body").unwrap();
        assert_eq!(plan.outcome, PatchOutcome::Appended);
        assert!(plan.before.unwrap().contains("@RTK.md"));
    }

    #[test]
    fn test_patch_plan_replaces_existing_region() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(
            &p,
            format!("preface\n\n{MANAGED_START}\nold body\n{MANAGED_END}\n\nepilogue\n"),
        )
        .unwrap();
        let plan = plan_managed_patch(&p, "new body").unwrap();
        assert_eq!(plan.outcome, PatchOutcome::Replaced);
        assert!(plan.before.unwrap().contains("old body"));
        assert!(plan.after.contains("new body"));
    }

    #[test]
    fn test_patch_plan_unchanged_when_identical() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        let body = "stable body";
        std::fs::write(&p, format!("{MANAGED_START}\n{body}\n{MANAGED_END}\n")).unwrap();
        let plan = plan_managed_patch(&p, body).unwrap();
        assert_eq!(plan.outcome, PatchOutcome::Unchanged);
    }

    #[test]
    fn test_patch_plan_errors_on_unbalanced_markers() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(&p, format!("preface\n{MANAGED_START}\norphan\n")).unwrap();
        assert!(plan_managed_patch(&p, "body").is_err());
    }

    #[test]
    fn test_apply_patch_preserves_surrounding_content_and_backs_up() {
        let dir = tempfile::tempdir().unwrap();
        let backup_dir = dir.path().join("backups");
        std::env::set_var("BLACKBOX_BACKUP_DIR", &backup_dir);

        let p = dir.path().join("CLAUDE.md");
        std::fs::write(
            &p,
            format!("@RTK.md\n\n{MANAGED_START}\nold\n{MANAGED_END}\n\n# user notes\n"),
        )
        .unwrap();

        let plan = plan_managed_patch(&p, "fresh").unwrap();
        let backup = apply_managed_patch(&plan).unwrap();
        assert!(backup.is_some(), "backup should be taken when file existed");

        let result = std::fs::read_to_string(&p).unwrap();
        assert!(result.starts_with("@RTK.md"), "RTK import preserved");
        assert!(result.contains("# user notes"), "user content preserved");
        assert!(result.contains("fresh"), "new managed body present");
        assert!(!result.contains("\nold\n"), "old managed body replaced");

        std::env::remove_var("BLACKBOX_BACKUP_DIR");
    }

    #[test]
    fn test_global_target_path_skips_unsupported() {
        assert!(global_target_path("copilot").is_none());
        assert!(global_target_path("vibe").is_none());
        assert!(global_target_path("claude").is_some());
        assert!(global_target_path("codex").is_some());
        assert!(global_target_path("gemini").is_some());
        assert!(global_target_path("agents").is_some());
    }

    #[test]
    fn test_all_bro_tools_listed() {
        let preamble = builtin_preamble("claude");
        let expected_tools = [
            "bro_exec", "bro_resume", "bro_wait", "bro_when_all", "bro_when_any",
            "bro_broadcast", "bro_status", "bro_dashboard", "bro_cancel",
            "bro_providers", "bro_brofile", "bro_team",
        ];
        for tool in &expected_tools {
            assert!(preamble.contains(tool), "Missing tool: {tool}");
        }
    }
}
