use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Built-in tool documentation rendered into CLAUDE.md / AGENTS.md / GEMINI.md.
///
/// These sections are generated by the server — not stored as knowledge entries.
/// They serve two purposes:
/// 1. Teach workflow patterns (HOW/WHEN/WHY), not just tool descriptions
/// 2. List all tools so deferred-loading LLMs discover them before improvising
pub const MANAGED_START: &str = "<!-- bb:managed-start -->";
pub const MANAGED_END: &str = "<!-- bb:managed-end -->";

/// Resolve global-memory destinations per provider. Returns `None` for
/// providers without a defined global memory file (copilot reads project
/// files only; vibe is intentionally unsupported per design).
///
/// Env overrides take precedence over defaults:
/// `BLACKBOX_GLOBAL_CLAUDE_MD`, `BLACKBOX_GLOBAL_CODEX_MD`,
/// `BLACKBOX_GLOBAL_GEMINI_MD`.
pub fn global_target_path(provider: &str) -> Option<Result<PathBuf>> {
    let resolve = |env_key: &str, default_fn: &dyn Fn() -> Result<PathBuf>| -> Result<PathBuf> {
        if let Ok(v) = std::env::var(env_key) {
            return Ok(PathBuf::from(v));
        }
        default_fn()
    };

    let home = || dirs::home_dir().context("home directory not found");

    match provider {
        "claude" => Some(resolve("BLACKBOX_GLOBAL_CLAUDE_MD", &|| {
            let h = home()?;
            let shared = h.join(".claude-shared");
            Ok(if shared.is_dir() {
                shared.join("CLAUDE.md")
            } else {
                h.join(".claude").join("CLAUDE.md")
            })
        })),
        // "agents" is the render umbrella that produces AGENTS.md content;
        // globally, the only auto-loading consumer is Codex.
        "codex" | "agents" => Some(resolve("BLACKBOX_GLOBAL_CODEX_MD", &|| {
            Ok(home()?.join(".codex").join("AGENTS.md"))
        })),
        "gemini" => Some(resolve("BLACKBOX_GLOBAL_GEMINI_MD", &|| {
            Ok(home()?.join(".gemini").join("GEMINI.md"))
        })),
        _ => None,
    }
}

/// A planned managed-region patch. Each variant carries exactly the data
/// relevant to its case — no optionals, no "this field is only set for
/// that outcome" foot-guns. `apply_managed_patch` pattern-matches on this
/// to do the right thing.
#[derive(Debug, Clone)]
pub enum PatchPlan {
    /// File didn't exist; will be created with `managed_block` as the
    /// entire contents.
    Create {
        path: PathBuf,
        managed_block: String,
    },
    /// File exists but has no markers; `managed_block` will be appended
    /// to `existing_file` (preserving hand-authored content above).
    Append {
        path: PathBuf,
        existing_file: String,
        managed_block: String,
    },
    /// File exists with markers; content between them will be replaced.
    /// `existing_block` includes both markers.
    Replace {
        path: PathBuf,
        existing_block: String,
        managed_block: String,
    },
    /// File exists with markers and their content already matches what
    /// we'd render; nothing to do.
    Unchanged { path: PathBuf },
}

impl PatchPlan {
    /// The new managed block that would be written. `Unchanged` returns
    /// `None` because the point of that variant is that we won't write.
    pub fn managed_block(&self) -> Option<&str> {
        match self {
            Self::Create { managed_block, .. }
            | Self::Append { managed_block, .. }
            | Self::Replace { managed_block, .. } => Some(managed_block),
            Self::Unchanged { .. } => None,
        }
    }

    /// Text that represents "what's there now," formatted for dry-run
    /// display. Semantics differ per variant: for Append this is the
    /// whole file (will be preserved); for Replace it's just the block
    /// between markers (will be replaced).
    pub fn before_text(&self) -> Option<&str> {
        match self {
            Self::Create { .. } | Self::Unchanged { .. } => None,
            Self::Append { existing_file, .. } => Some(existing_file),
            Self::Replace { existing_block, .. } => Some(existing_block),
        }
    }

    pub fn summary(&self) -> String {
        match self {
            Self::Create { path, managed_block } => {
                format!("CREATE {} ({} chars)", path.display(), managed_block.len())
            }
            Self::Append { path, existing_file, managed_block } => format!(
                "APPEND managed region to {} (existing {} chars, adding {} chars)",
                path.display(),
                existing_file.len(),
                managed_block.len()
            ),
            Self::Replace { path, existing_block, managed_block } => format!(
                "REPLACE managed region in {} ({} chars → {} chars)",
                path.display(),
                existing_block.len(),
                managed_block.len()
            ),
            Self::Unchanged { path } => format!("UNCHANGED {}", path.display()),
        }
    }
}

/// Compute what a managed-region patch would do without writing anything.
/// `managed_body` is the bbox-rendered content (without markers).
pub fn plan_managed_patch(file_path: &Path, managed_body: &str) -> Result<PatchPlan> {
    let managed_block = format!("{MANAGED_START}\n{}\n{MANAGED_END}", managed_body.trim_end());
    let path = file_path.to_path_buf();

    if !file_path.exists() {
        return Ok(PatchPlan::Create { path, managed_block });
    }

    let existing = fs::read_to_string(file_path)
        .with_context(|| format!("reading {}", file_path.display()))?;
    let (start_idx, end_idx) = find_marker_positions(&existing)?;

    match (start_idx, end_idx) {
        (Some(s), Some(e)) => {
            let existing_block = existing[s..e + MANAGED_END.len()].to_string();
            if existing_block == managed_block {
                Ok(PatchPlan::Unchanged { path })
            } else {
                Ok(PatchPlan::Replace { path, existing_block, managed_block })
            }
        }
        (None, None) => Ok(PatchPlan::Append {
            path,
            existing_file: existing,
            managed_block,
        }),
        _ => anyhow::bail!(
            "{}: unbalanced managed-region markers — refusing to patch",
            file_path.display()
        ),
    }
}

/// Apply a `PatchPlan`. Snapshots the original (when a file already exists
/// and we're actually changing it) to the backup directory before writing.
/// Returns the backup path, if a snapshot was taken.
pub fn apply_managed_patch(plan: &PatchPlan) -> Result<Option<PathBuf>> {
    match plan {
        // Nothing to do — and no empty backup dir, either.
        PatchPlan::Unchanged { .. } => Ok(None),

        PatchPlan::Create { path, managed_block } => {
            create_parent_dir(path);
            write_atomic(path, &format!("{managed_block}\n"))?;
            Ok(None)
        }

        PatchPlan::Append { path, existing_file, managed_block } => {
            let backup = Some(snapshot_file(path)?);
            let sep = if existing_file.ends_with("\n\n") || existing_file.is_empty() {
                ""
            } else if existing_file.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            create_parent_dir(path);
            write_atomic(path, &format!("{existing_file}{sep}{managed_block}\n"))?;
            Ok(backup)
        }

        PatchPlan::Replace { path, managed_block, .. } => {
            let backup = Some(snapshot_file(path)?);
            let full = fs::read_to_string(path)?;
            let (s, e) = find_marker_positions(&full)?;
            let s = s.expect("planned Replace requires markers");
            let e = e.expect("planned Replace requires markers");
            let mut out = String::with_capacity(full.len() + managed_block.len());
            out.push_str(&full[..s]);
            out.push_str(managed_block);
            out.push_str(&full[e + MANAGED_END.len()..]);
            if !out.ends_with('\n') {
                out.push('\n');
            }
            create_parent_dir(path);
            write_atomic(path, &out)?;
            Ok(backup)
        }
    }
}

fn create_parent_dir(path: &Path) {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).ok();
        }
    }
}

fn find_marker_positions(text: &str) -> Result<(Option<usize>, Option<usize>)> {
    let starts: Vec<_> = text.match_indices(MANAGED_START).collect();
    let ends: Vec<_> = text.match_indices(MANAGED_END).collect();
    if starts.len() > 1 || ends.len() > 1 {
        anyhow::bail!("multiple managed-region markers found");
    }
    Ok((starts.first().map(|(i, _)| *i), ends.first().map(|(i, _)| *i)))
}

/// Extract the body between `<!-- bb:managed-start -->` and
/// `<!-- bb:managed-end -->` markers in a memory file. Returns None if
/// the file has no balanced managed region. The returned slice excludes
/// the markers themselves and any trailing newline immediately after the
/// start marker / before the end marker.
///
/// Used by `bbox_absorb --scope=global` to read back the managed region
/// of provider global-memory files (which mix bbox-managed content with
/// user-authored content outside the markers — only the managed region
/// is bbox's territory).
pub fn extract_managed_region(content: &str) -> Option<&str> {
    let (start, end) = find_marker_positions(content).ok()?;
    let s = start?;
    let e = end?;
    if e <= s + MANAGED_START.len() {
        return None;
    }
    let inner = &content[s + MANAGED_START.len()..e];
    Some(inner.trim_matches('\n'))
}

/// Snapshot a file to `~/.local/state/blackbox/backups/<ISO-ts>/<filename>`.
/// Returns the destination path. Creates parent dirs as needed.
pub fn snapshot_file(src: &Path) -> Result<PathBuf> {
    let backup_root = backup_root()?;
    let stamp = chrono::Utc::now().format("%Y%m%dT%H%M%SZ").to_string();
    let dir = backup_root.join(stamp);
    fs::create_dir_all(&dir)?;
    let name = src
        .file_name()
        .context("source path has no file name")?;
    let dest = dir.join(name);
    fs::copy(src, &dest)
        .with_context(|| format!("backing up {} → {}", src.display(), dest.display()))?;
    Ok(dest)
}

fn backup_root() -> Result<PathBuf> {
    if let Ok(v) = std::env::var("BLACKBOX_BACKUP_DIR") {
        return Ok(PathBuf::from(v));
    }
    let state = dirs::state_dir()
        .or_else(|| dirs::home_dir().map(|h| h.join(".local/state")))
        .context("could not locate state dir")?;
    Ok(state.join("blackbox").join("backups"))
}

fn write_atomic(path: &Path, content: &str) -> Result<()> {
    let tmp = path.with_extension("md.tmp");
    let mut file = fs::File::create(&tmp)
        .with_context(|| format!("creating {}", tmp.display()))?;
    file.write_all(content.as_bytes())?;
    file.sync_all()?;
    drop(file);
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} → {}", tmp.display(), path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_patch_plan_creates_when_missing() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        let plan = plan_managed_patch(&p, "hello\nworld").unwrap();
        match plan {
            PatchPlan::Create { managed_block, .. } => {
                assert!(managed_block.contains(MANAGED_START));
                assert!(managed_block.contains(MANAGED_END));
                assert!(managed_block.contains("hello"));
            }
            other => panic!("expected Create, got {other:?}"),
        }
    }

    #[test]
    fn test_patch_plan_appends_when_no_markers() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(&p, "user prose\n@RTK.md\n").unwrap();
        let plan = plan_managed_patch(&p, "managed body").unwrap();
        match plan {
            PatchPlan::Append { existing_file, .. } => {
                assert!(existing_file.contains("@RTK.md"));
            }
            other => panic!("expected Append, got {other:?}"),
        }
    }

    #[test]
    fn test_patch_plan_replaces_existing_region() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(
            &p,
            format!("preface\n\n{MANAGED_START}\nold body\n{MANAGED_END}\n\nepilogue\n"),
        )
        .unwrap();
        let plan = plan_managed_patch(&p, "new body").unwrap();
        match plan {
            PatchPlan::Replace { existing_block, managed_block, .. } => {
                assert!(existing_block.contains("old body"));
                assert!(managed_block.contains("new body"));
            }
            other => panic!("expected Replace, got {other:?}"),
        }
    }

    #[test]
    fn test_patch_plan_unchanged_when_identical() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        let body = "stable body";
        std::fs::write(&p, format!("{MANAGED_START}\n{body}\n{MANAGED_END}\n")).unwrap();
        let plan = plan_managed_patch(&p, body).unwrap();
        assert!(matches!(plan, PatchPlan::Unchanged { .. }));
    }

    #[test]
    fn test_patch_plan_errors_on_unbalanced_markers() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("CLAUDE.md");
        std::fs::write(&p, format!("preface\n{MANAGED_START}\norphan\n")).unwrap();
        assert!(plan_managed_patch(&p, "body").is_err());
    }

    #[test]
    fn test_apply_patch_preserves_surrounding_content_and_backs_up() {
        let dir = tempfile::tempdir().unwrap();
        let backup_dir = dir.path().join("backups");
        std::env::set_var("BLACKBOX_BACKUP_DIR", &backup_dir);

        let p = dir.path().join("CLAUDE.md");
        std::fs::write(
            &p,
            format!("@RTK.md\n\n{MANAGED_START}\nold\n{MANAGED_END}\n\n# user notes\n"),
        )
        .unwrap();

        let plan = plan_managed_patch(&p, "fresh").unwrap();
        let backup = apply_managed_patch(&plan).unwrap();
        assert!(backup.is_some(), "backup should be taken when file existed");

        let result = std::fs::read_to_string(&p).unwrap();
        assert!(result.starts_with("@RTK.md"), "RTK import preserved");
        assert!(result.contains("# user notes"), "user content preserved");
        assert!(result.contains("fresh"), "new managed body present");
        assert!(!result.contains("\nold\n"), "old managed body replaced");

        std::env::remove_var("BLACKBOX_BACKUP_DIR");
    }

    #[test]
    fn test_global_target_path_skips_unsupported() {
        assert!(global_target_path("copilot").is_none());
        assert!(global_target_path("vibe").is_none());
        assert!(global_target_path("claude").is_some());
        assert!(global_target_path("codex").is_some());
        assert!(global_target_path("gemini").is_some());
        assert!(global_target_path("agents").is_some());
    }

}
